
runMode: debug

app:
  pageSize: 10
  jwtSecret: 132DD44

server:
  httpPort: 8888
  readTimeout: 60
  writeTimeout: 80

database:
  driver: mysql
  user: root
  password: root
  host: laradock_mysql
  port: 3306
  name: blog
  tablePrefix: blog_

redis:
  addr: 0.0.0.0:6379
  password:
  db: 0
  maxIdle: 30
  maxActive: 30
  idleTimeout: 200

